# Generated by Django 3.2.25 on 2024-03-23 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('protagonists', models.CharField(max_length=200, null=True)),
                ('poster', models.ImageField(null=True, upload_to='posters/')),
                ('trailer', models.FileField(null=True, upload_to='trailers/')),
                ('start_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Coming Up'), (2, 'Starting'), (3, 'Running'), (4, 'Finished')], default=1)),
                ('ranking', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Cannot have ranking below 0')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
    ]
